# Database configuration
database:
  host: "localhost"
  user_id: "root"
  password: ""
  dbname: "core"


# Routes configuration
routes:
  home: "/"
  login: "/login"
  register: "/register"
  logout: "/logout"