# Database configuration
database:
  host: localhost
  username: root
  password: 
  dbname: core

# Application settings
app:
  debug: true
  timezone: UTC

# Routes configuration
routes:
  home: "/"
  login: "/login"
  register: "/register"